### ISSUE TITLE
Devfalse or Devtrue driver not worked

### ISSUE THREAD

**Issue by LaFa777** [PHPSocialNetwork/phpfastcache#425]
###Configuration:

PhpFastCache version: ` V6-rc1 `
PHP version: ` 7.1.1 `
Operating system: ` windows 10 x64`

####Issue description:

When I try use ```Devfalse``` or ```Devtrue``` driver, php printed Fatal error.
Example:
```
D:\projects\phpfastcache\tests>php Psr16Adapter.test.php Devfalse
[PHPFASTCACHE API V1.2.4]
[Begin Test: 'Psr16Adapter helper']
---
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to phpFastCache\Drivers\Devfalse\Item::__construct() must be an instance of phpFastCache\Drivers\Devnull\Driver, instance of phpFastCache\Drivers\Devfalse\Driver given in D:\projects\phpfastcache\src\phpFastCache\Drivers\Devfalse\Item.php:37
Stack trace:
#0 [internal function]: phpFastCache\Drivers\Devfalse\Item->__construct(Object(phpFastCache\Drivers\Devfalse\Driver), 'test-key')
#1 D:\projects\phpfastcache\src\phpFastCache\Core\Pool\CacheItemPoolTrait.php(74): ReflectionClass->newInstanceArgs(Array)
#2 D:\projects\phpfastcache\src\phpFastCache\Helper\Psr16Adapter.php(175): phpFastCache\Drivers\Devfalse\Driver->getItem('test-key')
#3 D:\projects\phpfastcache\tests\Psr16Adapter.test.php(20): phpFastCache\Helper\Psr16Adapter->has('test-key')
#4 {main}
  thrown in D:\projects\phpfastcache\src\phpFastCache\Drivers\Devfalse\Item.php on line 37
 
...
```
It's a bug?

**Comment by Geolim4** [comment]
Hi,

I'm gonna test it.

Hang tight :)

**Comment by Geolim4** [comment]
Does it's working now ?

**Comment by LaFa777** [comment]
almost...
```
D:\projects\phpfastcache\tests>php Psr16Adapter.test.php Devtrue
[PHPFASTCACHE API V1.2.4]
[Begin Test: 'Psr16Adapter helper']
---
PHP Fatal error:  Uncaught Error: Undefined class constant 'DRIVER_TIME_WRAPPER_INDEX' in D:\projects\phpfastcache\src\phpFastCache\Drivers\Devtrue\Driver.php:85
Stack trace:
#0 D:\projects\phpfastcache\src\phpFastCache\Core\Pool\CacheItemPoolTrait.php(76): phpFastCache\Drivers\Devtrue\Driver->driverRead(Object(phpFastCache\Drivers\Devtrue\Item))
#1 D:\projects\phpfastcache\src\phpFastCache\Helper\Psr16Adapter.php(175): phpFastCache\Drivers\Devtrue\Driver->getItem('test-key')
#2 D:\projects\phpfastcache\tests\Psr16Adapter.test.php(20): phpFastCache\Helper\Psr16Adapter->has('test-key')
#3 {main}
  thrown in D:\projects\phpfastcache\src\phpFastCache\Drivers\Devtrue\Driver.php on line 85
```

**Comment by Geolim4** [comment]
Here you go :)

**Comment by LaFa777** [comment]
Wow, so fast :) all worked, thanks!

**Comment by Geolim4** [comment]
Great, have a nice day :)
