### ISSUE TITLE
Predis // Configuration issue

### ISSUE THREAD

**Issue by lexo13** [PHPSocialNetwork/phpfastcache#612]
**Configuration**
- **PhpFastCache version:**
7.0.0

- **PhpFastCache API version:**  
2.0.4

- **PHP version:** 
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

**Describe the bug**

```
#!/usr/bin/php

<?php
require __DIR__ . '/vendor/autoload.php';

use Phpfastcache\CacheManager;
$InstanceCache = CacheManager::getInstance('predis', [
    'host' => '51.254.154.211', //Default value
    'port' => 6379, //Default value
    'password' => null, //Default value
    'database' => null, //Default value
]);
```

```
PHP Fatal error:  Uncaught Phpfastcache\Exceptions\PhpfastcacheInvalidConfigurationException: Invalid option(s) for the config Phpfastcache\Config\ConfigurationOption: host, port, password, database in /home/franck/public_html/message_queuing_hh/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Config/ConfigurationOption.php:115
Stack trace:
#0 /home/franck/public_html/message_queuing_hh/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php(564): Phpfastcache\Config\ConfigurationOption->__construct(Array)
#1 /home/franck/public_html/message_queuing_hh/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/CacheManager.php(115): Phpfastcache\CacheManager::validateConfig(Array)
#2 /home/franck/public_html/message_queuing_hh/tt.php(10): Phpfastcache\CacheManager::getInstance('predis', Array)
#3 {main}
  thrown in /home/franck/public_html/message_queuing_hh/vendor/phpfastcache/phpfastcache/lib/Phpfastcache/Config/ConfigurationOption.php on line 115
```

**Comment by Geolim4** [comment]
Hello,

You used primitive arrays which is now deprecated as of v7.
Please read this:
https://github.com/PHPSocialNetwork/phpfastcache/blob/master/docs/migration/MigratingFromV6ToV7.md#configuration-option-type

Cheers,
Georges

**Comment by lexo13** [comment]
Hi,

OK, it's not a bug but your example is out of date

**Comment by Geolim4** [comment]
Indeed, I'll update them ASAP, thanks.

**Comment by Geolim4** [comment]
It's now fixed, thanks @lexo13  !
