### ISSUE TITLE
php 8.1 incompatibility: During inheritance of Iterator: Uncaught ErrorException:

### ISSUE THREAD

**Issue by mbiebl** [PHPSocialNetwork/phpfastcache#849]
Running php 8.1.2 with phpfastcache 8.1.0, I get the following exception

```
<br />
<b>Fatal error</b>:  During inheritance of Iterator: Uncaught ErrorException: Return type of Phpfastcache\Util\ArrayObject::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in www\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Util\ArrayObject.php:52
Stack trace:
#0 www\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Util\ArrayObject.php(27): exception_error_handler()
#1 www\vendor\composer\ClassLoader.php(571): include('...')
#2 www\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile()
#3 www\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Config\ConfigurationOption.php(30): Composer\Autoload\ClassLoader-&gt;loadClass()
#4 www\vendor\composer\ClassLoader.php(571): include('...')
#5 www\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile()
#6 www\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Config\Config.php(25): Composer\Autoload\ClassLoader-&gt;loadClass()
#7 www\vendor\composer\ClassLoader.php(571): include('...')
#8 www\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile()
#9 www\wwwroot\server.php(101): Composer\Autoload\ClassLoader-&gt;loadClass()
#10 {main} in <b>www\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Util\ArrayObject.php</b> on line <b>27</b><br />

```

**Comment by mbiebl** [comment]
Seems this has been fixed by #848.

Would be awesome to have a new release 8.1.1 with this fix included.
Unfortunately I can't upgrade to phpfastcache v9 just yet.
